---
- include: install_packages_Debian.yml
  sudo: yes
  when: ansible_os_family == 'Debian'

- include: install_packages_RedHat.yml
  sudo: yes
  when: ansible_os_family == 'RedHat'

- name: Clone liquidprompt
  git: "repo=https://github.com/nojhan/liquidprompt.git dest={{ liquidprompt_path }}"

- include: all-users.yml
  when: liquidprompt_enable_all_users == true

- include: specific-users.yml
  when: liquidprompt_enable_all_users == false
